import warnings
import language_tool_python
from .utils import language_detection
from lib.data import TestCase, Conversation
from .strategy_base import Strategy
from .logger import get_logger
from .utils_new import FileLoader

warnings.filterwarnings("ignore")

FileLoader._load_env_vars(__file__)
logger = get_logger("grammatical_strategies")

# This module implements grammatical strategies to analyze the agent response.
class GrammaticalStrategy(Strategy):
    def __init__(self, name: str = "grammatical_strategies", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        #self.__model_name = kwargs.get("model_name", "llama3")

    @staticmethod
    def grammarChecker(text):
        tool = language_tool_python.LanguageTool('en-US')
        result = tool.check(text)
        return result
    
    def evaluate(self, testcase:TestCase, conversation:Conversation):#agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the grammatical correctness in the response
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating Grammatical Errors...")
        if language_detection(conversation.agent_response[0]) == "en":
            grammar_check = GrammaticalStrategy.grammarChecker(conversation.agent_response[0])
            print("Grammar Check:",grammar_check)
            score = 0.0 if len(grammar_check) >= 1 else 1.0
            logger.info(f"Grammatical Score: {score}")
            return score
        logger.info("Language is not English, returning -1.")
        return -1.
    

#Test
# strategy = GrammaticalStrategy()
# response = "They is doing well"
# score = strategy.evaluate([response])
# print(f"Grammatical Score: {score}")
# del strategy
# This is working good!