from typing import Optional
import asyncio
import logging
import warnings
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer

from .similarity_match import SimilarityMatchStrategy
from .utils import detect_text, google_lang_translate, language_detection
from .logger import get_logger
from .strategy_base import Strategy

logger = get_logger("strategies")
# This module implements language strategies to analyze the agent response.
class LanguageStrategiesAsync(Strategy):
    def __init__(self, name: str = "language_strategies_async", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        self.__strategy_name = kwargs.get("strategy_name")
        self.embedding_model_name = kwargs.get("model_name", "thenlper/gte-small")
        self.embedding_model = SentenceTransformer(self.embedding_model_name)

    async def language_detect_gt(self, agent_response: str, expected_response: str) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses Google Translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :return: A score representing if the languages are the same
        """
        logger.info("Evaluating language coverage...")
        response_language = await detect_text(agent_response)
        expected_language = await detect_text(expected_response)
        score = 1.0 if response_language == expected_language else 0.0
        logger.info(f"Response language: {response_language}, Expected language: {expected_language}, Score: {score}")
        return score
    
    async def language_similarity_gt(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Google translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = await detect_text(agent_response)
        expected_language = await detect_text(expected_response)
        text_list = []
        if response_language !="en":
            response_translated = await google_lang_translate(agent_response)
        else:
            response_translated = agent_response
        if expected_language != "en":
            expected_response_translated = await google_lang_translate(expected_response)
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score
        
    async def evaluate(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        # score = await self.language_detect_gt(agent_response, expected_response)
        # print("Language Detection GT:", score)
        match self.__strategy_name:
            case "language_detect_gt":
                score = await self.language_detect_gt(agent_response, expected_response)
                # print("Language Detection:", score)
                # logger.info("Language Detection:", score)
                return score
            case "language_similarity_gt":
                score = await self.language_similarity_gt(agent_response, expected_response)
                # print("Language Similarity:", score)
                # logger.info("Language Similarity Google Translate:", score)
                return score

#Test
# lg_instance = LanguageStrategiesAsync(strategy_name="language_detect_gt")
# result = asyncio.run(lg_instance.evaluate("இந்தியா என்பது பரந்த பாரம்பரியமும் பண்பாடும் கொண்ட நாடாகும். இங்கு பல மதங்கள், மொழிகள் மற்றும் கலாசாரங்கள் ஒன்றிணைந்து வாழ்கின்றன.அது உலகிலேயே மிகப்பெரிய ஜனநாயக நாடாகும்.","இந்தியா ஒரு பன்முகம் கொண்ட கலாச்சார நாடு. மொழி, மதம், உணவு மற்றும் உடைமுறை அனைத்திலும் வெவ்வேறு பண்புகள் காணப்படுகின்றன. இது உலகின் மிகப் பெரிய ஜனநாயகமானது."))
# print(result)
# print("#########")
# result = asyncio.run(lg_instance.evaluate("இந்தியா என்பது பரந்த பாரம்பரியமும் பண்பாடும் கொண்ட நாடாகும். இங்கு பல மதங்கள், மொழிகள் மற்றும் கலாசாரங்கள் ஒன்றிணைந்து வாழ்கின்றன.அது உலகிலேயே மிகப்பெரிய ஜனநாயக நாடாகும்.","India is a land of vast heritage and culture. It is the largest democracy in the world with many religions, languages and cultures living together."))
# print(result)
# del lg_instance
# Language Strategy is fixed!