from pydantic import BaseModel, Field
from typing import Optional

class Response(BaseModel):
    """
    Represents a response (expected and predicted) from an AI agent
    for a given prompt.
    Attributes:
        expected (str): The expected response.
        predicted (str): The predicted response.
    """
    agent_said: str = Field(..., description="The response provided by the agent.")
    ground_truth: Optional[str] = Field(None, description="The expected response, aka, Ground truth.")
    gt_description: Optional[str] = Field(None, description="A description of the ground truth, if available.")

    def __init__(self, agent_said: str, ground_truth: Optional[str] = None,
                  gt_description: Optional[str] = None):
        """
        Initializes a Response instance.

        Args:
            ground_truth (Optional[str]): The expected response as said by a human.
            agent_said (str): The response generated by the agent.
            gt_description (Optional[str]): A description of the ground truth, if available.
        """
        super().__init__(ground_truth=ground_truth, 
                         agent_said=agent_said,
                         gt_description=gt_description)

    def __str__(self):
        """Returns a string representation of the response."""
        if self.gt_description:
            return f"Ground Truth: {self.ground_truth} ({self.gt_description})\nAgent Said: {self.agent_said}"
        
        return f"Ground Truth: {self.ground_truth}\nAgent Said: {self.agent_said}"
    
    def __repr__(self): 
        """Returns a string representation of the Response instance for debugging."""
        if self.gt_description:
            return (f"Response(ground_truth={self.ground_truth!r}, "
                    f"agent_said={self.agent_said!r}, "
                    f"gt_description={self.gt_description!r})")
        return (f"Response(ground_truth={self.ground_truth!r}, "
                f"agent_said={self.agent_said!r})")
    
    def __eq__(self, other):
        """
        Checks equality between two Response instances.
        Compares both expected and predicted responses.
        """
        if not isinstance(other, Response):
            return False
        return (self.ground_truth == other.ground_truth and
                self.agent_said == other.agent_said and
                self.gt_description == other.gt_description)
    
    def __hash__(self):
        """
        Returns a hash of the Response instance.
        Uses the hash of both expected and predicted responses.
        """
        return hash((self.ground_truth, self.agent_said, self.gt_description))
    