from .strategy_base import Strategy
from typing import Optional
import asyncio
import logging
import warnings
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer
from googletrans import Translator
import language_tool_python
from language_strategies import LanguageStrategies as ls

logging.basicConfig(
    level=logging.INFO,  
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(),  
        logging.FileHandler("analyzer_log.log")  
    ]
)

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")


# This module implements grammatical strategies to analyze the agent response.
class GrammaticalStrategy(Strategy):
    def __init__(self, name: str = "grammatical_strategies", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        #self.__model_name = kwargs.get("model_name", "llama3")

    def grammar_check(self, agent_response: str) -> float:
        """
        Check the grammatical correctness in the response
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating Grammatical Errors...")
        grammar_check = self.grammarChecker(agent_response)
        score = 0.0 if len(grammar_check) > 1 else 1.0
        logger.info(f"Grammatical Score: {score}")
        return score
    
    def grammarChecker(text):
        tool = language_tool_python.LanguageTool('en-US')
        result = tool.check(text)
        return result