from strategy_base import Strategy
from typing import Optional
import warnings
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer
from utils import language_detection
from logger import get_logger
import requests

import os 
from dotenv import load_dotenv
from os.path import join, dirname

dotenv_path = join(dirname(__file__), '.env')
load_dotenv(dotenv_path)

logger = get_logger("language-strategies-sync")
warnings.filterwarnings("ignore")


# This module implements language strategies to analyze the agent response.
class LanguageStrategiesSync(Strategy):
    def __init__(self, name: str = "language_strategies_sync", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        self.__strategy_name = kwargs.get("strategy_name")
        self.embedding_model_name = kwargs.get("model_name", "thenlper/gte-small")
        self.embedding_model = SentenceTransformer(self.embedding_model_name)
        self.sarvam_url = os.getenv("SARVAM_URL")
        if not self.sarvam_url:
            logger.warning("SARVAM_URL is not set in environment.")
        else:
            logger.info("SARVAM_URL is loaded from environment.")
    
    def language_detect_langdetect(self, prompt: str, agent_response: str) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses langdetect package.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :return: A score representing if the languages are the same
        """
        logger.info("Evaluating language coverage...")
        response_language = language_detection(agent_response)
        prompt_language = language_detection(prompt)
        score = 1.0 if response_language == prompt_language else 0.0
        logger.info(f"Response language: {response_language}, Prompt language: {prompt_language}, Score: {score}")
        return score
    
    def language_similarity_sarvam(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Sarvam AI.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = language_detection(agent_response)
        text_list = []
        if response_language !="en":
            response_translated = requests.post(f"{self.sarvam_url}/translate",params={"input_text": agent_response,"target_language": response_language})
        else:
            response_translated = agent_response
        expected_language = language_detection(expected_response)
        if expected_language != "en":
            expected_response_translated = requests.post(f"{self.sarvam_url}/translate",params={"input_text": expected_response,"target_language": expected_language})
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score
        
    def evaluate(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        match self.__strategy_name:
            case "language_detect_langdetect":
                score = self.language_detect_langdetect(agent_response, expected_response)
                logger.info("Language Detection: %s", score)
                return score
            case "language_similarity_sarvam":
                score = self.language_similarity_sarvam(agent_response, expected_response)
                logger.info("Language Similarity Sarvam: %s", score)
                return score

#Test
# lg_instance = LanguageStrategiesSync(strategy_name="language_similarity_sarvam")
# result = lg_instance.evaluate("இந்தியா என்பது பரந்த பாரம்பரியமும் பண்பாடும் கொண்ட நாடாகும். இங்கு பல மதங்கள், மொழிகள் மற்றும் கலாசாரங்கள் ஒன்றிணைந்து வாழ்கின்றன.அது உலகிலேயே மிகப்பெரிய ஜனநாயக நாடாகும்.","India is a land of vast heritage and culture. It is the largest democracy in the world with many religions, languages and cultures living together.")
# print(result)
# del lg_instance
# Language Strategy is fixed!