from strategy_base import Strategy
from typing import Optional
import asyncio
import logging
import warnings
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer
from similarity_match import SimilarityMatchStrategy
from utils import detect_text, google_lang_translate, language_detection, sarvam_translate

logging.basicConfig(
    level=logging.INFO,  
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(),  
        logging.FileHandler("analyzer_log.log")  
    ]
)

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")


# This module implements language strategies to analyze the agent response.
class LanguageStrategies(Strategy):
    def __init__(self, name: str = "language_strategies", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        self.embedding_model_name = kwargs.get("model_name", "thenlper/gte-small")
        self.embedding_model = SentenceTransformer(self.embedding_model_name)
        #self.__model_name = kwargs.get("model_name", "llama3")

    async def language_detect_gt(self, prompt: str, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses Google Translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating language coverage...")
        response_language = await detect_text(agent_response)
        prompt_language = await detect_text(prompt)
        score = 1.0 if response_language.lang == prompt_language.lang else 0.0
        logger.info(f"Response language: {response_language.lang}, Prompt language: {prompt_language.lang}, Score: {score}")
        return score
    
    def language_detect_langdetect(self, prompt: str, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language. This uses langdetect package.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating language coverage...")
        response_language = language_detection(agent_response)
        prompt_language = language_detection(prompt)
        score = 1.0 if response_language == prompt_language else 0.0
        logger.info(f"Response language: {response_language}, Prompt language: {prompt_language}, Score: {score}")
        return score
    
    async def language_similarity_gt(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Google translate.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = await detect_text(agent_response)
        text_list = []
        if response_language.lang !="en":
            response_translated = await google_lang_translate(agent_response)
        else:
            response_translated = agent_response
        if expected_response.lang != "en":
            expected_response_translated = await google_lang_translate(expected_response)
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score
    
    def language_similarity_sarvam(self, prompt: str, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language. This method uses Sarvam AI.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        response_language = language_detection(agent_response)
        text_list = []
        if response_language !="en":
            response_translated = sarvam_translate(agent_response)
        else:
            response_translated = agent_response
        expected_language = language_detection(expected_response)
        if expected_language != "en":
            expected_response_translated = sarvam_translate(expected_response)
        else:
            expected_response_translated = expected_response
        text_list = [response_translated, expected_response_translated]        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.75:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            logger.info("Low language similarity detected.")
            score = 0.0
        return score
        
    async def evaluate(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        score = self.language_detect_gt(agent_response, expected_response)
        print("Language Detection GT:", score)
        score = self.language_detect_langdetect(agent_response, expected_response)
        print("Language Detection:", score)
        score = self.language_similarity_gt(agent_response, expected_response)
        print("Language Similarity GT:", score)
        # score = self.language_similarity_sarvam(agent_response, expected_response)
        # print("Language Similarity Sarvam:", score)

#Test
lg_instance = LanguageStrategies()
result = asyncio.run(lg_instance.evaluate("இந்தியா என்பது பரந்த பாரம்பரியமும் பண்பாடும் கொண்ட நாடாகும். இங்கு பல மதங்கள், மொழிகள் மற்றும் கலாசாரங்கள் ஒன்றிணைந்து வாழ்கின்றன.அது உலகிலேயே மிகப்பெரிய ஜனநாயக நாடாகும்.","இந்தியா ஒரு பன்முகம் கொண்ட கலாச்சார நாடு. மொழி, மதம், உணவு மற்றும் உடைமுறை அனைத்திலும் வெவ்வேறு பண்புகள் காணப்படுகின்றன. இது உலகின் மிகப் பெரிய ஜனநாயகமானது."))
#print("#########")
#lg_instance.evaluate("இந்தியா என்பது பரந்த பாரம்பரியமும் பண்பாடும் கொண்ட நாடாகும். இங்கு பல மதங்கள், மொழிகள் மற்றும் கலாசாரங்கள் ஒன்றிணைந்து வாழ்கின்றன.அது உலகிலேயே மிகப்பெரிய ஜனநாயக நாடாகும்.","India is a land of vast heritage and culture. It is the largest democracy in the world with many religions, languages and cultures living together.")
del lg_instance
# Language Strategy to be fixed! - Language Similarity GT: <coroutine object LanguageStrategies.language_similarity_gt at 0x7434965e70a0>