from .strategy_base import Strategy
from typing import Optional
import asyncio
import logging
import warnings
from sentence_transformers.util import cos_sim
from sentence_transformers import SentenceTransformer
from googletrans import Translator

logging.basicConfig(
    level=logging.INFO,  
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(),  
        logging.FileHandler("analyzer_log.log")  
    ]
)

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")


# This module implements language strategies to analyze the agent response.
class LanguageStrategies(Strategy):
    def __init__(self, name: str = "language_strategies", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)
        self.embedding_model_name = kwargs.get("model_name", "thenlper/gte-small")
        self.embedding_model = SentenceTransformer(self.embedding_model_name)
        #self.__model_name = kwargs.get("model_name", "llama3")

    async def language_coverage(self, prompt: str, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language coverage by detecting the language used in the response and comparing it with the expected language.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating language coverage...")
        response_language = await self.detect_text(agent_response)
        prompt_language = await self.detect_text(prompt)
        score = 1.0 if response_language.lang == prompt_language.lang else 0.0
        logger.info(f"Response language: {response_language.lang}, Prompt language: {prompt_language.lang}, Score: {score}")
        return score
    
    async def language_similarity(self, prompt: str, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Check the language similarity by detecting the language used in the response and comparing it with the expected language.
        :param prompt: The prompt sent to the agent to generate the response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the language similarity
        """
        logger.info("Evaluating language similarity...")
        prompt_language = await self.detect_text(prompt)
        text_list = []
        if prompt_language!="en":
            response_translated = await self.google_lang_translate(agent_response)
            prompt_translated = await self.google_lang_translate(prompt)
            text_list = [response_translated, prompt_translated]
            if expected_response:
                expected_response_translated = await self.google_lang_translate(expected_response)
                text_list.append(expected_response_translated)
        else:
            text_list = [agent_response, prompt]
            if expected_response:
                text_list.append(expected_response)
        
        embeddings = self.embedding_model.encode(text_list)
        similarity = cos_sim(embeddings[0], embeddings[1])
        if similarity>=0.8:
            logger.info("High language similarity detected.")
            score = 1.0
        else:
            if expected_response:
                similarity_2 = cos_sim(embeddings[0], embeddings[2])
                if similarity_2 >= 0.8:
                    logger.info("High language similarity with expected response detected.")
                    score = 1.0
                else:
                    logger.info("Low language similarity detected.")
                    score = 0.0
            else:
                logger.info("Low language similarity detected.")
                score = 0.0
        return score
    
    async def detect_text(text):
        """
        Helper function to translate text to a specified language.
        """
        translator = Translator()
        try:
            language = await translator.detect(text)
            return language.lang
        except Exception as e:
            logger.error(f"Error in language detection: {e}")
            return "unknown"
    
    async def google_lang_translate(self, text: str, target_lang: str = "en") -> str:
        """
        Helper function to translate text to english language using Google Translate.
        :param text: The text to be translated.
        :param target_lang: The target language code (default is English
        return: The translated text in english
        """
        translator = Translator()
        try:
            translation = await translator.translate(text, dest=target_lang)
            return translation.text
        except Exception as e:
            logger.error(f"Error in translation: {e}")
            return text