from strategy_base import Strategy
import logging
import warnings
from lexical_diversity import lex_div

logging.basicConfig(
    level=logging.INFO,  
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[
        logging.StreamHandler(),  
        logging.FileHandler("analyzer_log.log")  
    ]
)

logger = logging.getLogger(__name__)

warnings.filterwarnings("ignore")


# This module implements lexical diversity to analyze the agent response.
class LexicalDiversity(Strategy):
    def __init__(self, name: str = "lexicaldiversity", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)

    def lexical_diversity_calculate(self, agent_response: str) -> float:
        """
        Check the lexical diversity in the response
        :param agent_response: The response generated by the agent.
        :return: A score representing the quality of the agent's response.
        """
        logger.info("Evaluating Lexical Diversity...")
        flt = lex_div.flemmatize(agent_response)
        score = lex_div.mattr(flt)
        logger.info(f"lexical_diversity score: {score}")
        return score
    
    def evaluate(self, agent_response, expected_response = None) -> float:
        """
        Evaluate the agent response for lexical diversity.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against (not used in this strategy).
        :return: A score representing the lexical diversity of the agent's response.
        """
        return self.lexical_diversity_calculate(agent_response)
    
#Test
# lD_instance = LexicalDiversity()
# score = lD_instance.evaluate("All the worlds a stage, and all the men and women merely players. They have their exits and their entrances; And one man in his time plays many parts.")
# print(f"Score: {score}")
# score = lD_instance.evaluate("Monky is wrote it!")
# print(f"Score: {score}")
# del lD_instance
# Lexical Diversity is working!