from strategy_base import Strategy
from typing import Optional
import warnings
from logger import get_logger
from utils import language_detection, sarvam_translate
from sentence_transformers import SentenceTransformer
from sentence_transformers.util import cos_sim

logger = get_logger("transliterated_language_strategy")
warnings.filterwarnings("ignore")


# This module implements ltransliterated languages to analyze the agent response.
class TransliteratedStrategy(Strategy):
    def __init__(self, name: str = "transliterated_language_strategy", **kwargs) -> None:
        super().__init__(name, kwargs=kwargs)

    def transliterate_text(self, text: str, expected_response:str) -> float:
        """
        Converts the transliterated text from English to the target language.
        :param text: The text to be transliterated.
        :return: The transliterated text.
        """
        language = language_detection(text)
        if language == "en":
            translated_language = sarvam_translate(text, target_lang=language)
            sentences = [translated_language, expected_response]
        else:
            sentences = [text, expected_response]

        model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-mpnet-base-v2')
        embeddings = model.encode(sentences)
        similarity = cos_sim(embeddings[0], embeddings[1])
        logger.info("The text similarity is:",similarity[0][0].item()) 
        
        return similarity[0][0]
        
    def evaluate(self, agent_response: str, expected_response: Optional[str] = None) -> float:
        """
        Evaluate the transliterated text by comparing it with the expected response.
        :param agent_response: The response generated by the agent.
        :param expected_response: The expected response to compare against.
        :return: A score representing the similarity of the transliterated text.
        """
        logger.info("Evaluating transliterated text...")
        score = self.transliterate_text(agent_response, expected_response)
        logger.info(f"Transliterated Score: {score}")
        return score

#Test
# tl_instance = TransliteratedStrategy()
# result = tl_instance.evaluate("என் தந்தை அவரது அறையில் இருக்கிறார்", "என் அப்பா அவர்களுடைய அறையில் உள்ளார்.")
# print(result)
# del tl_instance
# Language Strategy is fixed!